### ISSUE TITLE
预览可设置关闭

### ISSUE THREAD

**Issue by yorkfread** [xtab-app/xtab#3]
预览的画面现在是模糊的，还有些影响性能的感觉，个人感觉不是很必要，希望可以设置成关闭

 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by popeyelau** [comment]
另外建议适配下 dark mode.

**Comment by dangxuandev** [comment]
![ezgif-5-05591386ad0e](https://user-images.githubusercontent.com/5436704/56583610-9069bc00-660c-11e9-8f95-2df10274d054.gif)

@yorkfread @popeyelau 

这两个功能已经在 `1.0.6` 版本中实现，不过是作为付费功能开放

![image](https://user-images.githubusercontent.com/5436704/56583779-eb9bae80-660c-11e9-98a8-53b62343a9c2.png)


https://github.com/xtab-app/xtab/releases/tag/1.0.6
