### ISSUE TITLE
切换iOS模拟器会卡住

### ISSUE THREAD

**Issue by hh1myfei** [xtab-app/xtab#5]
如果是切换模拟器没有反应。

**Comment by dangxuandev** [comment]
![image](https://user-images.githubusercontent.com/5436704/56583539-5ef0f080-660c-11e9-9ce4-c421fb8d011f.png)

不知道是不是指这个，我切换了一下 

```
open -a Simulator
```

打开的模拟器没有问题。

可以升级到最新版再确认下问题是否仍然出现。
