### ISSUE TITLE
更新Relunch失败

### ISSUE THREAD

**Issue by ccj99** [xtab-app/xtab#6]
每次更新的时候Relunch都失败，没有手工启动的话，Relunch进程会吃很多CPU，系统卡死

**Comment by dangxuandev** [comment]
我刚手动重试了一下安装 `1.0.5` 自动更新到 `1.0.6`，Relunch 没有问题。

能提供更多信息么，操作系统版本之类的。另外你的应用是否是在 `/Application` 下执行的？

**Comment by ccj99** [comment]
> 我刚手动重试了一下安装 `1.0.5` 自动更新到 `1.0.6`，Relunch 没有问题。
> 
> 能提供更多信息么，操作系统版本之类的。另外你的应用是否是在 `/Application` 下执行的？

抱歉，`Mac mini 2018, macOS 10.14.4`，是在`/Application` 目录下，拉不起来问题不大，别卡死就行..

**Comment by dangxuandev** [comment]
@ccj99 在 https://github.com/xtab-app/xtab/releases/tag/1.0.12 已经修复，感谢反馈。

是上游依赖的库在某些情况下逻辑会进死循环造成的：https://github.com/macmade/GitHubUpdates/issues/109

**Comment by popeyelau** [comment]
@xcodebuild  怎么解决的？ 我也在用这个库
